AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getDevice:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::582142734153:role/jdmt-lambda-basic'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /device
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: '/device/{deviceId}'
            Method: GET
